name: maps

networks:
  default:
  homelab-net:
    external: true

volumes:
  config_volume:

services:
  mapproxy-config-generator:
    image: alpine
    env_file:
      - .env.local
    volumes:
      - ./mapproxy/config:/tmp
      - config_volume:/output
    command: >
      sh -c "
        apk add --no-cache gettext &&
        envsubst < /tmp/mapproxy.template.yaml > /output/mapproxy.yaml
      "

  mapproxy:
    container_name: mapproxy
    restart: unless-stopped
    image: ghcr.io/mapproxy/mapproxy/mapproxy:5.0.0-alpine-nginx
    depends_on:
      mapproxy-config-generator:
        condition: service_completed_successfully
    volumes:
      - config_volume:/mapproxy/config
      - ./mapproxy/cache_data:/mapproxy/cache_data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mapproxy.entrypoints=websecure"
      - "traefik.http.routers.mapproxy.rule=Host(`api.homelab.destructuring-bind.org`) && PathPrefix(`/mapproxy/wmts/wmts`)"
      - "traefik.http.services.mapproxy.loadbalancer.server.port=80"
      - "dockflare.enable=true"
      - "cloudflare.tunnel.enable=true"
      - "cloudflare.tunnel.hostname=api.destructuring-bind.org"
      - "cloudflare.tunnel.path=/mapproxy/wmts/wmts"
      - "cloudflare.tunnel.service=http://mapproxy:80"
    networks:
      - default
      - homelab-net

  uk-weather-overlays:
    container_name: uk_weather_overlays
    image: ghcr.io/rm-hull/metoffice-uk-weather-overlays:latest
    command:
      - api-server
      - "--root=/data/metoffice-datahub"
      - "--port=8080"
    volumes:
      - ./metoffice-datahub:/data/metoffice-datahub
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uk-weather-overlays.entrypoints=websecure"
      - "traefik.http.routers.uk-weather-overlays.rule=Host(`api.homelab.destructuring-bind.org`) && PathPrefix(`/v1/metoffice/datahub`)"
      - "traefik.http.services.uk-weather-overlays.loadbalancer.server.port=80"
      - "dockflare.enable=true"
      - "cloudflare.tunnel.enable=true"
      - "cloudflare.tunnel.hostname=api.destructuring-bind.org"
      - "cloudflare.tunnel.path=/v1/metoffice/datahub"
      - "cloudflare.tunnel.service=http://uk-weather-overlays:8080"
    networks:
      - default
      - homelab-net


